name: Build

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build Game
      run: |
        # Добавляем твою папку с компилятором в PATH
        export PATH=$PATH:$GITHUB_WORKSPACE/toolchain/bin
        
        # Запускаем сборку
        make
        
        # Если elf2xex тоже лежит в папке toolchain/bin, он просто сработает
        elf2xex horse_game.elf default.xex

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: game-xex
        path: default.xex
